Ruby_on_Rails/rorc1/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  resources :categories, except: [:destroy]

  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get 'signup', to: 'users#new'
  #! 'route' controller#action - this format
  # root 'application#hello'
  #! rails expects a 'hello' action inside 'application' controller

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

Ruby_on_Rails/rorc1/app/views/layouts/_footer.html.erb
<footer class="bg-body-tertiary p-2 mt-5 d-flex justify-content-evenly">
    <div class="d-flex flex-column justify-content-between">
        <h3>Friend App<h3>
        <p class="fs-6 fw-light">Designed with Bootstrap</p>
    </div>
    <div class="p-2 d-flex justify-content-evenly">
        <div>
            <div class="m-2 mx-4">Ruby</div>
            <div class="m-2 mx-4">Rails</div>
            <div class="m-2 mx-4">Github</div>
            <div class="m-2 mx-4">HTML</div>
        </div>
        <div>
            <div class="m-2 mx-4">Node</div>
            <div class="m-2 mx-4">Yarn</div>
            <div class="m-2 mx-4">JavaScript</div>
            <div class="m-2 mx-4">CSS</div>
        </div>
    </div>
</footer>

Ruby_on_Rails/rorc1/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
  <div class="container-fluid">
    <%= link_to 'Articles App', root_path, class: "navbar-brand" %>    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>

        <% if logged_in? %>
          <li class="nav-item">
            <% if current_user.admin? %>
              <%= link_to '(Admin) Profile', user_path(current_user), class: "nav-link" %>
            <% else %>
              <%= link_to 'Profile', user_path(current_user), class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", data: { "turbo-method": :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Login', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

Ruby_on_Rails/rorc1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rorc1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>