Ruby_on_Rails/rorc1/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  resources :categories, except: [:destroy]

  root 'pages#home'
  get 'about', to: 'pages#about'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # get 'signup', to: 'users#new'
  #! 'route' controller#action - this format
  # root 'application#hello'
  #! rails expects a 'hello' action inside 'application' controller

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

Ruby_on_Rails/rorc1/app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
end

Ruby_on_Rails/rorc1/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
      @category = Category.find(params[:id])
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
    end

    private

    # Only allow a list of trusted parameters through.
    def category_params
        params.require(:category).permit(:name)
    end
end

Ruby_on_Rails/rorc1/app/views/categories/_form.html.erb
<%= form_with(model: @category) do |form| %>
  <div class="mb-3">
    <%= form.label "Category name", style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

Ruby_on_Rails/rorc1/app/views/categories/index.html.erb
<div class="container mt-4">
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>

  <h1 class="text-center">List of all Categories</h1>
  
    <% @categories.each do |category| %>
    <div id="<%= dom_id category %>">
        <%= link_to category.name, category_path(category) %>
    </div>
    <% end %>

</div>

<%= render 'layouts/footer' %>

Ruby_on_Rails/rorc1/app/views/categories/new.html.erb
<div class="container">

  <h1>New category</h1>

  <%= render 'shared/errors', obj: @category %>


  <%= render "form", obj: @category %>

  <div>
    <%= link_to "Back to articles", articles_path %>
  </div>
</div>

<%= render 'layouts/footer' %>

Ruby_on_Rails/rorc1/app/views/categories/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= @category.name %>
</div>